// microfrontend-sample/cart/src/App.tsx
import React from 'react';
import ReactDOM from 'react-dom';
import faker from 'faker';

import './index.css';

const App = () => (
  <div className='cart-container'>
    <strong>Cart:</strong>
    <div>You have {faker.random.number(10)} items in the cart</div>
  </div>
);
ReactDOM.render(<App />, document.getElementById('cart-dev'));

// microfrontend-sample/host/src/App.tsx
import { render } from 'solid-js/web';
import 'products/ProductsIndex';
import 'cart/CartIndex';

import './index.css';

const App = () => (
  <div class='container'>
    <strong>Host</strong>
    <div id='products-dev'></div>
    <div id='cart-dev'></div>
  </div>
);
render(App, document.getElementById('app'));
