// microfrontend-sample/host/src/App.tsx
import { render } from 'solid-js/web';
import 'products/ProductsIndex';
import 'cart/CartIndex';

import './index.css';

const App = () => (
  <div class='container'>
    <strong>Host</strong>
    <div id='products-dev'></div>
    <div id='cart-dev'></div>
  </div>
);
render(App, document.getElementById('app'));

// microfrontend-dependencies/products/src/App.tsx
import React from 'react';
import ReactDOM from 'react-dom';
import { faker } from '@faker-js/faker';

import './index.css';

let products: any = [];
for (let i = 0; i < 5; i++) {
  const name = faker.commerce.productName();
  products.push(name);
}

const App = () => (
  <div className='products-container'>
    <strong>Products:</strong>
    {products.map((p) => {
      return <div key={p}>{p}</div>;
    })}
  </div>
);

ReactDOM.render(<App />, document.getElementById('products-dev'));
