// microfrontend-sample/cart/src/App.vue
<template>
  <div class="cart-container">
    <strong>Cart:</strong>
    <div>You have {{ cart.count }} items in the cart</div>
  </div>
</template>

<script lang="ts">
import { faker } from '@faker-js/faker';

export default {
  data() {
    return {
      cart: {
        count: faker.datatype.number(5),
      },
    };
  },
};
</script>

// microfrontend-sample/cart/src/App.tsx
import React from 'react';
import ReactDOM from 'react-dom';
import { faker } from '@faker-js/faker';

import './index.css';

const App = () => (
  <div className='cart-container'>
    <strong>Cart:</strong>
    <div>You have {faker.datatype.number(5)} items in the cart</div>
  </div>
);
ReactDOM.render(<App />, document.getElementById('cart-dev'));
